name: main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -race -v ./...

    - name: Test
      run: |
        # The test keys need to be 0600 to be loaded
        chmod 0600 test/testdata/account-*.key
        # Run tests
        go test -race -v ./...

    - name: "Staticcheck"
      uses: dominikh/staticcheck-action@v1.3.0
      with:
        version: "2023.1.3"
